web:
  image: fiflet/nginx
  ports:
    - "8080:80"
  volumes:
    - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - php
php:
  image: nmcteam/php56
  volumes:
    - ./src:/srv/fiflet
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
  links:
    - db
db:
  image: sameersbn/mysql
  volumes:
   - /var/lib/mysql
  environment:
   - DB_NAME=fiflet
   - DB_USER=espen
   - DB_PASS=oep
